(()=>{
'use strict';
// The stable game engine is loaded in place of the older engine before the next script tag executes.
const oldGame=document.querySelector('script[src="game.js"]');if(oldGame)oldGame.src='game-fixed.js';
const KEY='psAccountsV1',ACTIVE='psActiveAccount';
async function hash(text){try{if(window.crypto&&crypto.subtle){const data=new TextEncoder().encode(text),buf=await crypto.subtle.digest('SHA-256',data);return [...new Uint8Array(buf)].map(x=>x.toString(16).padStart(2,'0')).join('')}}catch(e){}let h=0;for(let i=0;i<text.length;i++)h=((h<<5)-h)+text.charCodeAt(i)|0;return String(h>>>0)}
function accounts(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch(e){return {}}}function put(a){localStorage.setItem(KEY,JSON.stringify(a))}
function readProgress(){return{coins:localStorage.psCoins,owned:localStorage.psOwned,kit:localStorage.psKit,shoe:localStorage.psShoe,best:localStorage.psBest,goals:localStorage.psGoals,score:localStorage.psScore,reward:localStorage.psReward,bonus:localStorage.psBonus}}
function clearProgress(){['psCoins','psOwned','psKit','psShoe','psBest','psGoals','psScore','psReward','psBonus'].forEach(k=>localStorage.removeItem(k))}function loadProgress(p){clearProgress();Object.entries(p||{}).forEach(([k,v])=>{if(v!==undefined&&v!==null)localStorage.setItem(k,v)})}
function ui(){const gate=document.createElement('div');gate.id='accountGate';gate.innerHTML='<div class="accountBox"><div class="accountLogo">PENALTY <span>SHOOTER</span></div><h2 id="accountTitle">Sign in</h2><p id="accountSub">Use your player name and password to keep your progress on this browser.</p><div class="accountField"><label>PLAYER NAME</label><input id="accountName" maxlength="18" autocomplete="username" placeholder="Enter your name"></div><div class="accountField"><label>PASSWORD</label><input id="accountPass" type="password" maxlength="64" autocomplete="current-password" placeholder="Enter your password"></div><button class="accountAction" id="accountGo">SIGN IN</button><button class="accountSecondary" id="accountSwitch">CREATE ACCOUNT</button><div class="accountError" id="accountError"></div><p class="accountHint">No email, phone number, or other personal details are required.</p></div>';document.body.appendChild(gate);return gate}
function profileChip(name){let old=document.getElementById('accountUser');if(old)old.remove();const el=document.createElement('div');el.id='accountUser';el.className='accountUser';el.innerHTML='👤 '+String(name).replace(/[&<>"']/g,'')+' <button type="button" id="accountLogout">ACCOUNT</button>';document.body.appendChild(el);document.getElementById('accountLogout').onclick=showAccount}
function showAccount(){const gate=document.getElementById('accountGate')||ui();gate.classList.remove('hidden');const title=gate.querySelector('#accountTitle'),sub=gate.querySelector('#accountSub'),go=gate.querySelector('#accountGo'),sw=gate.querySelector('#accountSwitch'),name=gate.querySelector('#accountName'),pass=gate.querySelector('#accountPass'),err=gate.querySelector('#accountError');let creating=false;title.textContent='Sign in';sub.textContent='Use your player name and password to keep your progress on this browser.';go.textContent='SIGN IN';sw.textContent='CREATE ACCOUNT';name.value='';pass.value='';err.textContent='';sw.onclick=()=>{creating=!creating;title.textContent=creating?'Create account':'Sign in';sub.textContent=creating?'Your progress will be saved to this player account on this browser.':'Enter your player name and password.';go.textContent=creating?'CREATE ACCOUNT':'SIGN IN';sw.textContent=creating?'BACK TO SIGN IN':'CREATE ACCOUNT'};go.onclick=async()=>{const n=name.value.trim(),p=pass.value;if(n.length<2||n.length>18){err.textContent='Name must be 2–18 characters.';return}if(p.length<4){err.textContent='Password must be at least 4 characters.';return}const key=n.toLowerCase(),all=accounts(),h=await hash(p);if(creating){if(all[key]){err.textContent='That player name already exists.';return}const progress={coins:localStorage.getItem('psCoins')||'250',owned:localStorage.getItem('psOwned')||'["starter"]',kit:localStorage.getItem('psKit')||'starter',shoe:localStorage.getItem('psShoe')||'basic',best:localStorage.getItem('psBest')||'0',goals:localStorage.getItem('psGoals')||'0',score:localStorage.getItem('psScore')||'0'};all[key]={name:n,passwordHash:h,progress};put(all);localStorage.setItem(ACTIVE,key);location.reload()}else{if(!all[key]||all[key].passwordHash!==h){err.textContent='Incorrect name or password.';return}localStorage.setItem(ACTIVE,key);loadProgress(all[key].progress);location.reload()}}}
function boot(){const active=localStorage.getItem(ACTIVE),all=accounts();if(active&&all[active]){loadProgress(all[active].progress);profileChip(all[active].name);hookAutoSave(active);return}showAccount()}
function hookAutoSave(active){setInterval(()=>{const all=accounts();if(!all[active])return;all[active].progress=readProgress();put(all)},1200);addEventListener('beforeunload',()=>{const all=accounts();if(all[active]){all[active].progress=readProgress();put(all)}})}
boot();
})();