(()=>{
'use strict';
// Always load the mobile engine with a fresh URL so GitHub Pages/CDN cannot keep the old broken script.
const oldGame=document.querySelector('script[src="game.js"]');if(oldGame)oldGame.src='game-mobile.js?v=phone4';
const KEY='psAccountsV1',ACTIVE='psActiveAccount';
const safe=v=>String(v??'').replace(/[&<>"']/g,'');
async function hash(text){try{if(window.crypto&&crypto.subtle){const data=new TextEncoder().encode(text),buf=await crypto.subtle.digest('SHA-256',data);return [...new Uint8Array(buf)].map(x=>x.toString(16).padStart(2,'0')).join('')}}catch(e){}let h=0;for(let i=0;i<text.length;i++)h=((h<<5)-h)+text.charCodeAt(i)|0;return String(h>>>0)}
function accounts(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch(e){return {}}}
function put(a){try{localStorage.setItem(KEY,JSON.stringify(a));return true}catch(e){return false}}
function readProgress(){return{coins:localStorage.getItem('psCoins')||'250',owned:localStorage.getItem('psOwned')||'["starter"]',kit:localStorage.getItem('psKit')||'starter',shoe:localStorage.getItem('psShoe')||'basic',best:localStorage.getItem('psBest')||'0',goals:localStorage.getItem('psGoals')||'0',score:localStorage.getItem('psScore')||'0',reward:localStorage.getItem('psReward')||'',bonus:localStorage.getItem('psBonus')||'0'}}
function clearProgress(){['psCoins','psOwned','psKit','psShoe','psBest','psGoals','psScore','psReward','psBonus'].forEach(k=>localStorage.removeItem(k))}
function loadProgress(p){clearProgress();const d={coins:'250',owned:'["starter"]',kit:'starter',shoe:'basic',best:'0',goals:'0',score:'0',reward:'',bonus:'0'};Object.assign(d,p||{});Object.entries(d).forEach(([k,v])=>localStorage.setItem('ps'+k.charAt(0).toUpperCase()+k.slice(1),String(v)))}
function ui(){let gate=document.getElementById('accountGate');if(gate)return gate;gate=document.createElement('div');gate.id='accountGate';gate.innerHTML='<div class="accountBox"><div class="accountLogo">PENALTY <span>SHOOTER</span></div><h2 id="accountTitle">Sign in</h2><p id="accountSub">Sign in to save your football progress.</p><div class="accountField"><label>PLAYER NAME</label><input id="accountName" maxlength="18" autocomplete="username" autocapitalize="none" spellcheck="false" placeholder="Enter player name"></div><div class="accountField"><label>PASSWORD</label><input id="accountPass" type="password" maxlength="64" autocomplete="current-password" placeholder="Enter password"></div><button class="accountAction" id="accountGo" type="button">SIGN IN</button><button class="accountSecondary" id="accountSwitch" type="button">CREATE ACCOUNT</button><div class="accountError" id="accountError"></div><p class="accountHint">Your progress is stored on this browser.</p></div>';document.body.appendChild(gate);return gate}
function profileChip(name){let old=document.getElementById('accountUser');if(old)old.remove();const el=document.createElement('div');el.id='accountUser';el.className='accountUser';el.innerHTML='👤 <span>'+safe(name)+'</span><button type="button" id="accountLogout">ACCOUNT</button>';document.body.appendChild(el);const b=document.getElementById('accountLogout');if(b)b.onclick=showAccount}
function showAccount(){const gate=ui();gate.classList.remove('hidden');const title=gate.querySelector('#accountTitle'),sub=gate.querySelector('#accountSub'),go=gate.querySelector('#accountGo'),sw=gate.querySelector('#accountSwitch'),name=gate.querySelector('#accountName'),pass=gate.querySelector('#accountPass'),err=gate.querySelector('#accountError');let creating=false;title.textContent='Sign in';sub.textContent='Sign in to save your football progress.';go.textContent='SIGN IN';sw.textContent='CREATE ACCOUNT';name.value='';pass.value='';err.textContent='';sw.onclick=()=>{creating=!creating;title.textContent=creating?'Create account':'Sign in';sub.textContent=creating?'Create a player profile on this browser.':'Sign in to save your football progress.';go.textContent=creating?'CREATE ACCOUNT':'SIGN IN';sw.textContent=creating?'BACK TO SIGN IN':'CREATE ACCOUNT';pass.value='';err.textContent='';name.focus()};go.onclick=async()=>{const n=name.value.trim(),p=pass.value;if(!/^[\p{L}\p{N}_ -]{2,18}$/u.test(n)){err.textContent='Use 2–18 letters, numbers, spaces, _ or -.';return}if(p.length<4){err.textContent='Password must be at least 4 characters.';return}go.disabled=true;const key=n.toLowerCase(),all=accounts(),h=await hash(p);if(creating){if(all[key]){err.textContent='That player name already exists.';go.disabled=false;return}all[key]={name:n,passwordHash:h,progress:readProgress()};put(all);localStorage.setItem(ACTIVE,key);location.reload();return}if(!all[key]||all[key].passwordHash!==h){err.textContent='Incorrect player name or password.';go.disabled=false;return}localStorage.setItem(ACTIVE,key);loadProgress(all[key].progress);location.reload()};name.onkeydown=e=>{if(e.key==='Enter')pass.focus()};pass.onkeydown=e=>{if(e.key==='Enter')go.click()};setTimeout(()=>name.focus(),50)}
function boot(){try{const active=localStorage.getItem(ACTIVE),all=accounts();if(active&&all[active]){loadProgress(all[active].progress);profileChip(all[active].name);hookAutoSave(active);return}}catch(e){}showAccount()}
function hookAutoSave(active){setInterval(()=>{const all=accounts();if(!all[active])return;all[active].progress=readProgress();put(all)},1200);addEventListener('beforeunload',()=>{const all=accounts();if(all[active]){all[active].progress=readProgress();put(all)}})}
boot();
})();