(()=>{'use strict';
const $=id=>document.getElementById(id), canvas=$('gameCanvas');
if(!canvas)return;
const ctx=canvas.getContext('2d'); if(!ctx)return;
let W=0,H=0,state='menu',difficulty=localStorage.getItem('psDifficulty')||'medium',mode='shootout';
let shots=0,goals=0,score=0,streak=0,level=1,power=.2,powerDir=1,ax=0,ay=.55,shot=null,keeperX=0,keeperTarget=0;
let coins=Number(localStorage.getItem('psCoins')||250),kit=localStorage.getItem('psKit')||'starter';
const cfg={easy:{save:.12,error:.38,speed:.10},medium:{save:.34,error:.22,speed:.23},hard:{save:.58,error:.10,speed:.42}};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function resize(){W=innerWidth;H=innerHeight;const d=Math.min(devicePixelRatio||1,2);canvas.width=W*d;canvas.height=H*d;canvas.style.width=W+'px';canvas.style.height=H+'px';ctx.setTransform(d,0,0,d,0,0)}
addEventListener('resize',resize,{passive:true});resize();
function show(id){$(id)?.classList.remove('hidden')} function hide(id){$(id)?.classList.add('hidden')}
function text(id,v){const e=$(id);if(e)e.textContent=v}
function message(t,c=''){const e=$('message');if(e){e.textContent=t;e.className='message '+c}}
function goal(){const mobile=W<650,w=Math.min(W*(mobile?.88:.74),620),h=Math.min(H*(mobile?.30:.31),245);return{l:W/2-w/2,t:mobile?Math.max(112,H*.16):H*.20,w,h}}
function hud(){text('coins',Math.floor(coins));text('level',level);text('statGoals',Number(localStorage.getItem('psGoals')||0));text('statScore',Number(localStorage.getItem('psScore')||0));text('statBest',Number(localStorage.getItem('psBest')||0));text('statStreak',streak);const p=$('powerFill');if(p)p.style.width=(power*100)+'%'}
function updateDifficultyUI(){['easy','medium','hard'].forEach(d=>$(d+'Keeper')?.classList.toggle('active',d===difficulty));const e=$('difficultyInfo');if(e)e.innerHTML=difficulty.toUpperCase()+' • '+(difficulty==='easy'?'slow reactions':difficulty==='medium'?'balanced reactions':'fast, accurate reactions')+' • <strong>NO COINS</strong>'}
function startGame(selectedMode){mode=selectedMode||'shootout';shots=0;goals=0;score=0;streak=0;level=1;state='aim';ax=0;ay=.55;power=.2;powerDir=1;shot=null;keeperX=0;keeperTarget=0;hide('menu');hide('result');hide('store');hide('statsPanel');hide('skillsPanel');hide('settingsPanel');show('controls');message(difficulty.toUpperCase()+' KEEPER • NO COINS','info');hud()}
function backMenu(){state='menu';hide('controls');hide('result');show('menu');updateDifficultyUI();message('Choose keeper difficulty')}
function setDifficulty(d){difficulty=d;localStorage.setItem('psDifficulty',d);updateDifficultyUI();message(d.toUpperCase()+' KEEPER SELECTED • NO COINS','info')}
function openPanel(id){show(id)}
function aimMove(dx,dy){if(state!=='aim')return;ax=clamp(ax+dx,-1,1);ay=clamp(ay+dy,.02,1)}
function shoot(){if(state!=='aim')return;shots++;const c=cfg[difficulty],p=power,spread=Math.max(.012,(1-p)*.08+.01);const tx=clamp(ax+(Math.random()-.5)*spread,-1.12,1.12),ty=clamp(ay+(Math.random()-.5)*spread*.8,.02,1.08);const edge=Math.min(1,Math.hypot(tx*.9,(ty-.5)*1.3));let chance=clamp(c.save+(shots-1)*.018-edge*.30,.02,.92);if(difficulty==='easy')chance=Math.min(chance,.35);if(difficulty==='medium')chance=Math.min(chance,.68);if(difficulty==='hard')chance=Math.max(chance,.28);const saved=Math.random()<chance;keeperTarget=saved?tx+(Math.random()-.5)*c.error:clamp(tx+(Math.random()-.5)*c.error*3,-1,1);shot={t:0,dur:.62+.20*(1-p),tx,ty,saved,miss:Math.abs(tx)>1.03||ty<.02||ty>1.03};state='flight';message('SHOT!','info')}
function finishShot(){if(!shot)return;const s=shot;shot=null;const scored=!s.saved&&!s.miss;if(scored){goals++;streak++;score+=100+goals*25;const oldGoals=Number(localStorage.getItem('psGoals')||0),oldScore=Number(localStorage.getItem('psScore')||0),oldBest=Number(localStorage.getItem('psBest')||0);localStorage.setItem('psGoals',oldGoals+1);localStorage.setItem('psScore',oldScore+score);localStorage.setItem('psBest',Math.max(oldBest,score));message('GOAL!','good')}else{streak=0;message(s.saved?'SAVED!':'MISS!','bad')}hud();setTimeout(()=>{state='result';hide('controls');show('result');text('resultTitle',scored?'GOAL!':s.saved?'SAVED!':'MISS!');text('resultText','Goals: '+goals+(mode==='shootout'||mode==='tournament'?' / 5':'')+' • Score: '+score+' • '+difficulty.toUpperCase()+' KEEPER • NO COINS')},350)}
function nextShot(){state='aim';ax=0;ay=.55;power=.2;powerDir=1;shot=null;keeperX=0;keeperTarget=0;hide('result');show('controls');message('AIM YOUR SHOT','info');hud()}
function resetProgress(){['psCoins','psOwned','psKit','psShoe','psBest','psGoals','psScore'].forEach(k=>localStorage.removeItem(k));location.reload()}
function handle(id){switch(id){case'shootoutBtn':case'bottomPlay':startGame('shootout');break;case'tournamentBtn':startGame('tournament');break;case'challengeBtn':startGame('challenge');break;case'easyKeeper':setDifficulty('easy');break;case'mediumKeeper':setDifficulty('medium');break;case'hardKeeper':setDifficulty('hard');break;case'shootBtn':shoot();break;case'leftBtn':aimMove(-.11,0);break;case'rightBtn':aimMove(.11,0);break;case'upBtn':aimMove(0,-.09);break;case'downBtn':aimMove(0,.09);break;case'spinLeft':aimMove(-.06,0);break;case'spinRight':aimMove(.06,0);break;case'nextBtn':nextShot();break;case'restartBtn':startGame(mode);break;case'backMenuBtn':backMenu();break;case'statsBtn':openPanel('statsPanel');break;case'bottomRank':openPanel('statsPanel');break;case'skillsBtn':openPanel('skillsPanel');break;case'storeBtn':openPanel('store');renderStore();break;case'settingsBtn':openPanel('settingsPanel');break;case'resetBtn':resetProgress();break}}
document.addEventListener('click',e=>{const b=e.target.closest?.('button');if(!b||b.disabled)return;if(b.dataset.close){hide(b.dataset.close);return}if(b.id)handle(b.id)},false);
document.addEventListener('touchend',e=>{const b=e.target.closest?.('button');if(!b||b.disabled||b.dataset.touchFired)return;b.dataset.touchFired='1';setTimeout(()=>delete b.dataset.touchFired,500)}, {passive:true});
function renderStore(){const box=$('shopGrid');if(!box)return;box.innerHTML='';[['starter','Starter Kit',0],['redkit','Crimson Kit',180],['neonkit','Neon Pro',320]].forEach(([id,name,cost])=>{const b=document.createElement('button');b.type='button';b.className='buyBtn';b.textContent=id===kit?'EQUIPPED':'🪙 '+cost;b.addEventListener('click',()=>{if(cost&&coins<cost){message('Not enough coins','bad');return}if(cost&&id!==kit)coins-=cost;kit=id;localStorage.setItem('psKit',kit);localStorage.setItem('psCoins',coins);renderStore();hud()});box.appendChild(b)})}
let dragging=false;
canvas.addEventListener('pointerdown',e=>{if(state!=='aim')return;dragging=true;canvas.setPointerCapture?.(e.pointerId);setAim(e.clientX,e.clientY);e.preventDefault()},{passive:false});canvas.addEventListener('pointermove',e=>{if(dragging)setAim(e.clientX,e.clientY)},{passive:false});addEventListener('pointerup',()=>dragging=false,{passive:true});
function setAim(x,y){const r=canvas.getBoundingClientRect(),q=goal();x-=r.left;y-=r.top;if(x<q.l-90||x>q.l+q.w+90||y<q.t-90||y>q.t+q.h+90)return;ax=clamp((x-q.l-q.w/2)/(q.w/2),-1,1);ay=clamp((y-q.t)/q.h,.02,1)}
function draw(){const q=goal();ctx.fillStyle='#061522';ctx.fillRect(0,0,W,H);ctx.fillStyle='#155d36';ctx.fillRect(0,H*.34,W,H*.66);ctx.fillStyle='#ffffff09';ctx.fillRect(q.l,q.t,q.w,q.h);ctx.strokeStyle='#fff';ctx.lineWidth=W<650?5:7;ctx.strokeRect(q.l,q.t,q.w,q.h);ctx.strokeStyle='#ffffff25';ctx.lineWidth=1;for(let i=1;i<15;i++){const x=q.l+q.w*i/15;ctx.beginPath();ctx.moveTo(x,q.t);ctx.lineTo(x,q.t+q.h);ctx.stroke()}let px=W/2,py=H*.77,bx=px,by=py,br=W<650?14:18;if(shot){const e=clamp(shot.t/shot.dur,0,1),s=e*e*(3-2*e),tx=W/2+shot.tx*q.w*.43,ty=q.t+shot.ty*q.h;bx=px+(tx-px)*s;by=py+(ty-py)*s-Math.sin(s*Math.PI)*H*.06;br+=8*s;keeperX+=(keeperTarget-keeperX)*cfg[difficulty].speed}const kx=W/2+keeperX*q.w*.45;ctx.fillStyle='#15945e';ctx.fillRect(kx-18,q.t+q.h*.5,36,48);ctx.fillStyle='#d99b78';ctx.beginPath();ctx.arc(kx,q.t+q.h*.5-25,17,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#15945e';ctx.lineWidth=11;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(kx-12,q.t+q.h*.52);ctx.lineTo(kx-45-keeperX*18,q.t+q.h*.70);ctx.moveTo(kx+12,q.t+q.h*.52);ctx.lineTo(kx+45+keeperX*18,q.t+q.h*.70);ctx.stroke();ctx.fillStyle=kit==='redkit'?'#b52a3b':kit==='neonkit'?'#22d878':'#176bd0';ctx.fillRect(px-19,H*.69-18,38,48);ctx.fillStyle='#f5f7f7';ctx.beginPath();ctx.arc(bx,by,br,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#222';ctx.lineWidth=1;ctx.stroke();if(state==='aim'){const tx=W/2+ax*q.w*.43,ty=q.t+ay*q.h;ctx.strokeStyle='#ffe52d';ctx.lineWidth=2;ctx.setLineDash([7,6]);ctx.beginPath();ctx.moveTo(bx,by);ctx.lineTo(tx,ty);ctx.stroke();ctx.setLineDash([]);ctx.beginPath();ctx.arc(tx,ty,19+Math.sin(Date.now()/130)*3,0,Math.PI*2);ctx.stroke()}}
let last=performance.now();function loop(now){const dt=Math.min(.033,(now-last)/1000);last=now;if(state==='aim'){power+=powerDir*dt*.9;if(power>=1){power=1;powerDir=-1}if(power<=.08){power=.08;powerDir=1}hud()}if(state==='flight'&&shot){shot.t+=dt;if(shot.t>=shot.dur)finishShot()}draw();requestAnimationFrame(loop)}
updateDifficultyUI();hud();requestAnimationFrame(loop);window.PenaltyShooter={start:startGame,menu:backMenu,shoot,chooseDifficulty:setDifficulty};
})();