const $=id=>document.getElementById(id);
const scene=new THREE.Scene();scene.background=new THREE.Color(0x78add2);
const camera=new THREE.PerspectiveCamera(60,innerWidth/innerHeight,.1,100);
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.shadowMap.enabled=true;$('#game').appendChild(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xffffff,0x24542d,2.5));const sun=new THREE.DirectionalLight(0xffffff,3);sun.position.set(-8,15,12);sun.castShadow=true;scene.add(sun);
const M=c=>new THREE.MeshStandardMaterial({color:c,roughness:.7}),grass=M(0x17763b),white=M(0xf7f7f2),blue=M(0x1768c5),yellow=M(0xffa51a),skin=M(0xb87550),black=M(0x11151a);
const field=new THREE.Mesh(new THREE.PlaneGeometry(38,72),grass);field.rotation.x=-Math.PI/2;field.position.z=-8;field.receiveShadow=true;scene.add(field);
const GW=7.32,GH=2.44,GZ=-3.8,DEP=1.9;
function box(w,h,d,m,x,y,z){const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);o.position.set(x,y,z);o.castShadow=true;scene.add(o)}box(.15,GH,.15,white,-GW/2,GH/2,GZ);box(.15,GH,.15,white,GW/2,GH/2,GZ);box(GW,.15,.15,white,0,GH,GZ);
const nm=new THREE.LineBasicMaterial({color:0xffffff,transparent:true,opacity:.8});function ln(a,b){scene.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints([a,b]),nm))}for(let x=-GW/2;x<=GW/2;x+=.45)ln(new THREE.Vector3(x,0,GZ-DEP),new THREE.Vector3(x,GH,GZ-DEP));for(let y=0;y<=GH;y+=.3)ln(new THREE.Vector3(-GW/2,y,GZ-DEP),new THREE.Vector3(GW/2,y,GZ-DEP));for(let x=-GW/2;x<=GW/2;x+=.6)ln(new THREE.Vector3(x,GH,GZ),new THREE.Vector3(x,GH,GZ-DEP));
function person(color,z){const g=new THREE.Group();const body=new THREE.Mesh(new THREE.CylinderGeometry(.55,.62,1.1,16),color);body.position.y=1.25;g.add(body);const head=new THREE.Mesh(new THREE.SphereGeometry(.35,20,16),skin);head.position.y=2.2;g.add(head);for(const x of[-.23,.23]){const leg=new THREE.Mesh(new THREE.CylinderGeometry(.15,.15,.8,12),black);leg.position.set(x,.55,0);g.add(leg);const boot=new THREE.Mesh(new THREE.BoxGeometry(.28,.14,.55),black);boot.position.set(x,.08,-.08);g.add(boot)}for(const x of[-.72,.72]){const arm=new THREE.Mesh(new THREE.CylinderGeometry(.16,.16,.95,12),color);arm.position.set(x,1.35,0);arm.rotation.z=x<0?-.85:.85;g.add(arm);const glove=new THREE.Mesh(new THREE.SphereGeometry(.21,16,12),white);glove.position.set(x*1.5,1.7,0);g.add(glove)}g.position.z=z;g.traverse(o=>o.castShadow=true);scene.add(g);return g}
const player=person(blue,6.25),keeper=person(yellow,GZ+.3);const ball=new THREE.Mesh(new THREE.SphereGeometry(.46,32,24),M(0xffffff));ball.castShadow=true;scene.add(ball);
let level=1,score=0,goals=0,shots=0,ax=0,ay=.5,power=.05,pdir=1,spin=0,shooting=false,finished=false,hold=false,vel=new THREE.Vector3();
function hud(){$('level').textContent=level;$('score').textContent=score;$('goals').textContent=goals;$('shots').textContent=shots;$('powerFill').style.width=(power*100)+'%'}function msg(t,c=''){$('message').textContent=t;$('message').className='message '+c}
function reset(){ball.position.set(0,.46,6.25);vel.set(0,0,0);ax=0;ay=.5;power=.05;pdir=1;spin=0;shooting=false;finished=false;keeper.position.x=0;hud()}
function start(){level=1;score=0;goals=0;shots=0;$('menu').classList.add('hidden');$('controls').classList.remove('hidden');$('result').classList.add('hidden');reset();msg('Aim, then hold SHOOT for power','info')}
function next(){if(shots&&shots%5===0)level++;$('result').classList.add('hidden');reset();msg('Aim, then hold SHOOT for power','info')}
function end(goal,saved){if(finished)return;finished=true;shooting=false;if(goal){goals++;score+=100*level;msg('GOAL! +'+100*level,'good')}else msg(saved?'SAVED!':'MISS!','bad');hud();setTimeout(()=>{$('resultTitle').textContent=goal?'GOAL!':'NO GOAL';$('resultText').textContent='Goals: '+goals+' • Shots: '+shots+' • Level: '+level;$('result').classList.remove('hidden')},350)}
function aim(x,y){if(shooting)return;ax=THREE.MathUtils.clamp((x/innerWidth-.5)*2,-1,1);ay=THREE.MathUtils.clamp(1-y/innerHeight,.05,1)}
function kick(){if(shooting||finished)return;shooting=true;shots++;const target=new THREE.Vector3(ax*3.3,.35+ay*2,GZ);vel.copy(target.sub(ball.position).normalize().multiplyScalar(10+power*15));vel.y+=power*2;msg('SHOT!','info');hud()}
function bind(id,fn){const e=$(id);if(!e)return;e.addEventListener('pointerdown',ev=>{ev.preventDefault();ev.stopPropagation();fn(ev)},{passive:false});e.addEventListener('touchstart',ev=>{ev.preventDefault();ev.stopPropagation();fn(ev)},{passive:false})}
bind('shootoutBtn',start);bind('endlessBtn',start);bind('nextBtn',next);bind('restartBtn',start);bind('leftBtn',()=>ax=THREE.MathUtils.clamp(ax-.12,-1,1));bind('rightBtn',()=>ax=THREE.MathUtils.clamp(ax+.12,-1,1));bind('upBtn',()=>ay=THREE.MathUtils.clamp(ay+.1,0,1));bind('spinLeft',()=>spin=THREE.MathUtils.clamp(spin-.15,-1,1));bind('spinRight',()=>spin=THREE.MathUtils.clamp(spin+.15,-1,1));
const sb=$('shootBtn');function down(e){e.preventDefault();e.stopPropagation();if(!shooting&&!finished)hold=true}function up(e){e.preventDefault();e.stopPropagation();if(hold){hold=false;kick()}}if(sb){sb.addEventListener('pointerdown',down,{passive:false});sb.addEventListener('pointerup',up,{passive:false});sb.addEventListener('pointercancel',up,{passive:false});sb.addEventListener('touchstart',down,{passive:false});sb.addEventListener('touchend',up,{passive:false})}
let drag=false;renderer.domElement.addEventListener('pointerdown',e=>{if(shooting||finished)return;drag=true;aim(e.clientX,e.clientY)});renderer.domElement.addEventListener('pointermove',e=>{if(drag)aim(e.clientX,e.clientY)});renderer.domElement.addEventListener('pointerup',()=>drag=false);renderer.domElement.addEventListener('pointercancel',()=>drag=false);
window.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'||e.key.toLowerCase()==='a')ax=THREE.MathUtils.clamp(ax-.08,-1,1);if(e.key==='ArrowRight'||e.key.toLowerCase()==='d')ax=THREE.MathUtils.clamp(ax+.08,-1,1);if(e.key==='ArrowUp'||e.key.toLowerCase()==='w')ay=THREE.MathUtils.clamp(ay+.08,0,1);if(e.key==='ArrowDown'||e.key.toLowerCase()==='s')ay=THREE.MathUtils.clamp(ay-.08,0,1);if(e.code==='Space'&&!e.repeat)kick()});
const clock=new THREE.Clock();function loop(){requestAnimationFrame(loop);const dt=Math.min(clock.getDelta(),.033),t=performance.now()/1000;if(!shooting&&!finished){power+=pdir*dt*.9;if(power>=1){power=1;pdir=-1}if(power<=.05){power=.05;pdir=1}hud()}if(shooting&&!finished){vel.y-=9.81*dt;vel.multiplyScalar(1-.025*dt);vel.x+=spin*2.2*dt;ball.position.addScaledVector(vel,dt);ball.rotation.x+=vel.z*dt;ball.rotation.z-=vel.x*dt;if(ball.position.y<.46){ball.position.y=.46;vel.y*=-.45;vel.x*=.86;vel.z*=.86}keeper.position.x=THREE.MathUtils.damp(keeper.position.x,Math.sin(t*(1+level*.12))*2.05,5.5+level*.3,dt);if(ball.position.z<=GZ+.08){const inside=Math.abs(ball.position.x)<GW/2-.1&&ball.position.y>0&&ball.position.y<GH;const saved=Math.abs(ball.position.x-keeper.position.x)<1&&Math.abs(ball.position.y-1.3)<.9;end(inside&&!saved,saved)}if(ball.position.z<GZ-DEP-1)end(false,false)}else ball.position.y=.46+Math.sin(t*3)*.02;camera.position.set(ax*.7,4.35,16.8);camera.lookAt(0,1.2,GZ-.1);renderer.render(scene,camera)}reset();loop();window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});