(()=>{
'use strict';
const $=id=>document.getElementById(id),canvas=$('gameCanvas');
if(!canvas)return;
const ctx=canvas.getContext('2d');
let W=innerWidth,H=innerHeight,dpr=1,state='menu',mode='shootout',difficulty=localStorage.getItem('psDifficulty')||'medium';
let shots=0,goals=0,score=0,streak=0,level=1,power=.1,pdir=1,aimX=0,aimY=.55,spin=0,shot=null,keeperX=0,keeperTarget=0,flash=0,shake=0;
let coins=Number(localStorage.getItem('psCoins')||250),owned=[];
try{owned=JSON.parse(localStorage.getItem('psOwned')||'["starter"]')}catch(e){owned=['starter']}
let kit=localStorage.getItem('psKit')||'starter',shoe=localStorage.getItem('psShoe')||'basic';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const cfg={easy:{save:.16,speed:.13,error:.34},medium:{save:.40,speed:.22,error:.18},hard:{save:.64,speed:.34,error:.08}};
const items=[['starter','Starter Kit','shirt','👕',0,'#176bd0','Classic blue kit'],['redkit','Crimson Kit','shirt','👕',180,'#b52a3b','Better accuracy'],['neonkit','Neon Pro','shirt','👕',320,'#22d878','Best accuracy'],['speed','Speed Boots','shoes','👟',220,'#eee','More power'],['gold','Gold Boots','shoes','🥾',450,'#e9b62b','More power'],['curve','Curve Boots','shoes','⚽',600,'#48a9ff','More curve']];
function save(){localStorage.setItem('psCoins',Math.floor(coins));localStorage.setItem('psOwned',JSON.stringify(owned));localStorage.setItem('psKit',kit);localStorage.setItem('psShoe',shoe);localStorage.setItem('psDifficulty',difficulty)}
function resize(){dpr=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;canvas.width=W*dpr;canvas.height=H*dpr;canvas.style.width=W+'px';canvas.style.height=H+'px';ctx.setTransform(dpr,0,0,dpr,0,0)}
addEventListener('resize',resize,{passive:true});resize();
function text(id,v){const e=$(id);if(e)e.textContent=v}
function hud(){text('coins',Math.floor(coins));text('level',level);const p=$('powerFill');if(p)p.style.width=(power*100)+'%';const x=$('xpFill');if(x)x.style.width=Math.min(100,20+goals*12)+'%';text('statGoals',Number(localStorage.getItem('psGoals')||0));text('statScore',Number(localStorage.getItem('psScore')||0));text('statBest',Number(localStorage.getItem('psBest')||0));text('statStreak',streak)}
function msg(t,c=''){const e=$('message');if(e){e.textContent=t;e.className='message '+c}}
function show(id){const e=$(id);if(e)e.classList.remove('hidden')}
function hide(id){const e=$(id);if(e)e.classList.add('hidden')}
function goalRect(){const m=W<650,gw=Math.min(W*(m?.9:.74),620),gh=Math.min(H*(m?.30:.31),245);return{left:W/2-gw/2,top:m?H*.15:H*.20,gw,gh}}
function updateDifficultyUI(){['easyKeeper','mediumKeeper','hardKeeper'].forEach(id=>{const e=$(id);if(e)e.classList.toggle('active',id===difficulty+'Keeper')});msg('KEEPER: '+difficulty.toUpperCase()+' • NO COINS','info')}
function chooseDifficulty(d){difficulty=d;save();updateDifficultyUI()}
function start(m){mode=m;level=1;shots=0;goals=0;score=0;streak=0;hide('menu');resetShot();msg('AIM • DRAG THE TARGET • TAP SHOOT','info')}
function resetShot(){state='aim';aimX=0;aimY=.55;spin=0;power=.1;pdir=1;shot=null;keeperX=0;keeperTarget=0;show('controls');hide('result');hud()}
function menu(){state='menu';hide('controls');hide('result');show('menu');updateDifficultyUI()}
function bind(id,fn){const e=$(id);if(!e)return;e.onclick=e.ontouchend=null;let last=0;const fire=ev=>{if(ev){ev.preventDefault?.();ev.stopPropagation?.()}const now=Date.now();if(now-last<220)return;last=now;fn()};e.addEventListener('pointerup',fire,{passive:false});e.addEventListener('click',fire,{passive:false})}
[['shootoutBtn',()=>start('shootout')],['tournamentBtn',()=>start('tournament')],['challengeBtn',()=>start('challenge')],['easyKeeper',()=>chooseDifficulty('easy')],['mediumKeeper',()=>chooseDifficulty('medium')],['hardKeeper',()=>chooseDifficulty('hard')],['shootBtn',shoot],['leftBtn',()=>move(-.11,0)],['rightBtn',()=>move(.11,0)],['upBtn',()=>move(0,-.09)],['downBtn',()=>move(0,.09)],['spinLeft',()=>spinMove(-.18)],['spinRight',()=>spinMove(.18)],['nextBtn',next],['restartBtn',()=>start(mode)],['backMenuBtn',menu],['bottomPlay',()=>start('shootout')],['bottomRank',()=>show('statsPanel')],['statsBtn',()=>show('statsPanel')],['skillsBtn',()=>show('skillsPanel')],['storeBtn',()=>{renderShop();show('store')}],['settingsBtn',()=>show('settingsPanel')]].forEach(([id,fn])=>bind(id,fn));
function move(dx,dy){if(state!=='aim')return;aimX=clamp(aimX+dx,-1,1);aimY=clamp(aimY+dy,.02,1)}
function spinMove(v){if(state==='aim')spin=clamp(spin+v,-1,1)}
function shoot(){if(state!=='aim')return;shots++;const c=cfg[difficulty]||cfg.medium,p=power,accuracy=kit==='neonkit'?.035:kit==='redkit'?.018:0,bonus=shoe==='gold'?.05:shoe==='speed'?.025:0,spread=Math.max(.012,(1-p)*.085+.012)-accuracy,tx=clamp(aimX+(Math.random()-.5)*spread,-1.12,1.12),ty=clamp(aimY+(Math.random()-.5)*spread*.8,.02,1.08);const edge=Math.min(1,Math.hypot(tx*.82,(ty-.5)*1.35));const saveChance=clamp(c.save+(level-1)*.025+Math.random()*.09-edge*.25,.05,.94);const saved=Math.random()<saveChance;const kx=saved?tx+(Math.random()-.5)*c.error:clamp(tx+(Math.random()-.5)*.45,-1,1);const ky=saved?ty+(Math.random()-.5)*c.error*.6:clamp(ty+(Math.random()-.5)*.5,.02,1);shot={t:0,dur:.58+.25*(1-p)-bonus,tx,ty,kx,ky,saved,miss:Math.abs(tx)>1.03||ty<.02||ty>1.03};keeperTarget=kx;state='flight';msg('SHOT!','info')}
function afterShot(){if(!shot)return;const s=shot;shot=null;const scored=!s.saved&&!s.miss;if(scored){goals++;streak++;const pts=100*level+streak*25;score+=pts;localStorage.setItem('psGoals',Number(localStorage.getItem('psGoals')||0)+1);localStorage.setItem('psScore',Number(localStorage.getItem('psScore')||0)+pts);localStorage.setItem('psBest',Math.max(Number(localStorage.getItem('psBest')||0),score));flash=1;shake=5;msg('GOAL!','good')}else{streak=0;shake=3;msg(s.saved?'SAVED!':'MISS!','bad')}
// Keeper difficulty modes never award coins.
save();hud();setTimeout(()=>{if((mode==='shootout'||mode==='tournament')&&shots>=5){const won=goals>=3;finishResult(won?'ROUND WON':'ROUND LOST','Goals: '+goals+' / 5 • Score: '+score+' • '+difficulty.toUpperCase()+' KEEPER • NO COINS')}else finishResult(scored?'GOAL!':s.saved?'SAVED!':'MISS!','Goals: '+goals+' • Streak: '+streak+' • '+difficulty.toUpperCase()+' KEEPER')},450)}
function finishResult(t,b){state='result';text('resultTitle',t);text('resultText',b);show('result')}
function next(){if((mode==='shootout'||mode==='tournament')&&shots>=5){level++;shots=0;goals=0;streak=0}resetShot()}
function renderShop(){const box=$('shopGrid');if(!box)return;box.innerHTML='';items.forEach(i=>{const has=owned.includes(i[0]),active=i[2]==='shirt'?kit===i[0]:shoe===i[0],el=document.createElement('div');el.className='shopItem';el.innerHTML='<div class="itemIcon">'+i[3]+'</div><b>'+i[1]+'</b><small>'+i[6]+'</small><button type="button" class="buyBtn '+(active?'owned':'')+'">'+(active?'EQUIPPED':has?'EQUIP':'🪙 '+i[4])+'</button>';box.appendChild(el);bindElement(el.querySelector('button'),()=>{if(!has){if(coins<i[4]){msg('Not enough coins','bad');return}coins-=i[4];owned.push(i[0])}if(i[2]==='shirt')kit=i[0];else shoe=i[0];save();renderShop();hud()})})}
function bindElement(e,fn){if(!e)return;let last=0;const fire=ev=>{ev.preventDefault?.();ev.stopPropagation?.();if(Date.now()-last<220)return;last=Date.now();fn()};e.addEventListener('pointerup',fire,{passive:false});e.addEventListener('click',fire,{passive:false})}
document.querySelectorAll('.close').forEach(b=>bindElement(b,()=>hide(b.dataset.close)));bind('resetBtn',()=>{['psCoins','psOwned','psKit','psShoe','psDifficulty'].forEach(k=>localStorage.removeItem(k));location.reload()});
let drag=false;function point(x,y){const r=canvas.getBoundingClientRect();return{x:x-r.left,y:y-r.top}}
function aimAt(x,y){if(state!=='aim')return;const g=goalRect();if(x<g.left-80||x>g.left+g.gw+80||y<g.top-80||y>g.top+g.gh+80)return;aimX=clamp((x-g.left-g.gw/2)/(g.gw/2),-1,1);aimY=clamp((y-g.top)/g.gh,.02,1)}
canvas.addEventListener('pointerdown',e=>{if(state!=='aim')return;drag=true;canvas.setPointerCapture?.(e.pointerId);const p=point(e.clientX,e.clientY);aimAt(p.x,p.y);e.preventDefault()},{passive:false});canvas.addEventListener('pointermove',e=>{if(!drag)return;const p=point(e.clientX,e.clientY);aimAt(p.x,p.y);e.preventDefault()},{passive:false});['pointerup','pointercancel','pointerleave'].forEach(n=>canvas.addEventListener(n,()=>drag=false));
function stadium(){const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#061522');g.addColorStop(.42,'#1b4257');g.addColorStop(.44,'#247b45');g.addColorStop(1,'#07502c');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.fillStyle='#132a36';for(let i=0;i<18;i++)ctx.fillRect(i*W/18,H*.16,W/18-2,H*.17);ctx.fillStyle='#0d6938';ctx.fillRect(0,H*.33,W,H*.67)}
function goal(){const g=goalRect();ctx.fillStyle='#ffffff09';ctx.fillRect(g.left,g.top,g.gw,g.gh);ctx.strokeStyle='#fff';ctx.lineWidth=W<650?5:7;ctx.strokeRect(g.left,g.top,g.gw,g.gh);ctx.strokeStyle='#ffffff2c';ctx.lineWidth=1;for(let i=1;i<18;i++){const x=g.left+g.gw*i/18;ctx.beginPath();ctx.moveTo(x,g.top);ctx.lineTo(x,g.top+g.gh);ctx.stroke()}for(let i=1;i<10;i++){const y=g.top+g.gh*i/10;ctx.beginPath();ctx.moveTo(g.left,y);ctx.lineTo(g.left+g.gw,y);ctx.stroke()}return g}
function person(x,y,color,s,keeper){ctx.save();ctx.translate(x,y);ctx.scale(s,s);if(keeper)ctx.rotate((keeperTarget-keeperX)*.08);ctx.fillStyle='#0006';ctx.beginPath();ctx.ellipse(0,72,30,8,0,0,Math.PI*2);ctx.fill();ctx.fillStyle=color;ctx.fillRect(-20,-18,40,50);ctx.fillStyle='#d99b78';ctx.beginPath();ctx.arc(0,-39,18,0,Math.PI*2);ctx.fill();ctx.fillStyle='#231916';ctx.beginPath();ctx.arc(0,-49,17,Math.PI,Math.PI*2);ctx.fill();ctx.strokeStyle=color;ctx.lineWidth=11;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(-15,-3);ctx.lineTo(keeper?-43-(keeperTarget-keeperX)*18:-34,28);ctx.moveTo(15,-3);ctx.lineTo(keeper?43+(keeperTarget-keeperX)*18:34,28);ctx.stroke();ctx.strokeStyle='#202020';ctx.lineWidth=10;ctx.beginPath();ctx.moveTo(-9,31);ctx.lineTo(-15,69);ctx.moveTo(9,31);ctx.lineTo(15,69);ctx.stroke();ctx.restore()}
function ball(x,y,r){ctx.fillStyle='#f6f8f8';ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#222';ctx.lineWidth=Math.max(1,r*.1);ctx.stroke()}
function draw(now){ctx.save();if(shake)ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);stadium();const g=goal();keeperX+=(keeperTarget-keeperX)*(shot?cfg[difficulty].speed:.08);person(W/2+keeperX*g.gw*.45,g.top+g.gh*.68,'#15945e',W<650?.82:1,true);let sx=W/2,sy=H*.77,tx=W/2+aimX*g.gw*.43,ty=g.top+aimY*g.gh,bx=sx,by=sy,br=W<650?14:18;if(shot){const q=clamp(shot.t/shot.dur,0,1),e=q*q*(3-2*q);tx=W/2+shot.tx*g.gw*.43;ty=g.top+shot.ty*g.gh;bx=sx+(tx-sx)*e+Math.sin(e*Math.PI)*spin*g.gw*.09;by=sy+(ty-sy)*e-Math.sin(e*Math.PI)*H*(W<650?.055:.08);br+=8*e}const pc=(items.find(i=>i[0]===kit)||items[0])[5];person(W/2,H*.69,pc,W<650?.88:1.12,false);ball(bx,by,br);if(state==='aim'){ctx.strokeStyle='#ffe52d';ctx.lineWidth=2;ctx.setLineDash([7,6]);ctx.beginPath();ctx.moveTo(bx,by);ctx.lineTo(tx,ty);ctx.stroke();ctx.setLineDash([]);ctx.strokeStyle='#ffe52d';ctx.beginPath();ctx.arc(tx,ty,19+Math.sin(now/130)*3,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#ffe52d';ctx.font='900 10px Arial';ctx.textAlign='center';ctx.fillText('AIM',tx,ty-28)}if(flash){ctx.fillStyle='rgba(255,255,255,'+(flash*.12)+')';ctx.fillRect(g.left,g.top,g.gw,g.gh)}ctx.restore()}
let last=performance.now();function loop(now){const dt=Math.min(.033,(now-last)/1000);last=now;if(state==='aim'){power+=pdir*dt*.95;if(power>=1){power=1;pdir=-1}if(power<=.08){power=.08;pdir=1}hud()}if(state==='flight'&&shot){shot.t+=dt;if(shot.t>=shot.dur)afterShot()}if(shake){shake*=Math.pow(.04,dt);if(shake<.1)shake=0}flash=Math.max(0,flash-dt*2);draw(now);requestAnimationFrame(loop)}
updateDifficultyUI();hud();requestAnimationFrame(loop);
})();