(()=>{
'use strict';
const $=id=>document.getElementById(id),c=$('gameCanvas');
if(!c){return}const ctx=c.getContext('2d');if(!ctx){return}
let W=innerWidth,H=innerHeight,dpr=1,state='menu',mode='shootout',level=1,score=0,goals=0,shots=0,streak=0,power=.15,pdir=1,aimX=0,aimY=.58,spin=0,shot=null,particles=[],shake=0,flash=0,coins=Number(localStorage.psCoins||250);let keeper={x:0,target:0,dive:0};
const items=[['starter','Starter Kit','shirt','👕',0,'#176bd0','Classic blue kit'],['redkit','Crimson Kit','shirt','👕',180,'#b52a3b','+5% accuracy'],['neonkit','Neon Pro','shirt','👕',320,'#22d878','+10% accuracy'],['speed','Speed Boots','shoes','👟',220,'#eee','+8% power'],['gold','Gold Boots','shoes','🥾',450,'#e9b62b','+15% power'],['curve','Curve Boots','shoes','⚽',600,'#48a9ff','+20% curve']];
let owned;try{owned=JSON.parse(localStorage.psOwned||'["starter"]')}catch(e){owned=['starter']};let kit=localStorage.psKit||'starter',shoe=localStorage.psShoe||'basic';const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function save(){localStorage.psCoins=coins;localStorage.psOwned=JSON.stringify(owned);localStorage.psKit=kit;localStorage.psShoe=shoe}
function resize(){dpr=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;c.width=W*dpr;c.height=H*dpr;c.style.width=W+'px';c.style.height=H+'px';ctx.setTransform(dpr,0,0,dpr,0,0)}addEventListener('resize',resize);resize();
function msg(t,cl){const e=$('message');if(e){e.textContent=t;e.className='message '+(cl||'')}}
function stats(){const g=Number(localStorage.psGoals||0),s=Number(localStorage.psScore||0),b=Number(localStorage.psBest||0);if($('statGoals'))$('statGoals').textContent=g;if($('statScore'))$('statScore').textContent=s;if($('statBest'))$('statBest').textContent=b;if($('statStreak'))$('statStreak').textContent=streak;if($('skillAccuracy'))$('skillAccuracy').style.width=clamp(38+g*3,38,88)+'%';if($('skillPower'))$('skillPower').style.width=(shoe==='gold'?88:shoe==='speed'?76:55)+'%';if($('skillCurve'))$('skillCurve').style.width=(shoe==='curve'?88:shoe==='gold'?62:48)+'%'}
function hud(){if($('level'))$('level').textContent=level;if($('coins'))$('coins').textContent=Math.floor(coins);if($('powerFill'))$('powerFill').style.width=(power*100)+'%';if($('xpFill'))$('xpFill').style.width=Math.min(100,20+goals*9)+'%';stats()}
function reset(){aimX=0;aimY=.58;spin=0;power=.15;pdir=1;shot=null;keeper.x=0;keeper.target=0;keeper.dive=0;particles=[];shake=0;flash=0;state='aim';$('controls').classList.remove('hidden');$('result').classList.add('hidden');msg('Drag the target • tap SHOOT','info');hud()}
function start(m){mode=m;level=1;score=0;goals=0;shots=0;streak=0;$('menu').classList.add('hidden');reset()}
function backMenu(){state='menu';$('controls').classList.add('hidden');$('result').classList.add('hidden');$('menu').classList.remove('hidden');msg('Choose a mode')}
function showResult(t,x){state='result';$('resultTitle').textContent=t;$('resultText').textContent=x;$('result').classList.remove('hidden')}
function burst(x,y,n){for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,s=60+Math.random()*180;particles.push({x:x,y:y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,r:2+Math.random()*3,life:.5+Math.random()*.6})}}
function shoot(){if(state!=='aim')return;shots++;const p=power,skill=kit==='neonkit'?.035:kit==='redkit'?.018:0,bonus=shoe==='gold'?.06:shoe==='speed'?.03,spread=Math.max(.015,(1-p)*.1+.018)-skill,tx=clamp(aimX+(Math.random()-.5)*Math.max(.012,spread),-1.12,1.12),ty=clamp(aimY+(Math.random()-.5)*Math.max(.018,spread),.01,1.08),saveChance=clamp(.16+(level-1)*.07+Math.random()*.12,.1,.72),saved=Math.random()<saveChance,kx=saved?tx+(Math.random()-.5)*.16:clamp(tx+(Math.random()-.5)*.7,-1,1),ky=saved?ty+(Math.random()-.5)*.12:clamp(ty+(Math.random()-.5)*.55,.03,1);shot={t:0,dur:.62+.22*(1-p)-bonus*.15,tx,ty,kx,ky,saved,miss:Math.abs(tx)>1.03||ty<.02||ty>1.03};keeper.target=kx;keeper.dive=saved?(Math.sign(kx-keeper.x)||1):0;state='flight';msg('SHOT!','info')}
function finish(){if(!shot)return;const s=shot;shot=null;const ok=!s.saved&&!s.miss;if(ok){goals++;streak++;const pts=100*level+streak*25,reward=50+level*10;score+=pts;coins+=reward;localStorage.psGoals=Number(localStorage.psGoals||0)+1;localStorage.psScore=Number(localStorage.psScore||0)+pts;localStorage.psBest=Math.max(Number(localStorage.psBest||0),score);flash=1;shake=7;burst(W/2+s.tx*W*.3,H*.28+s.ty*H*.18,35);msg('GOAL! +'+reward+' 🪙','good')}else{streak=0;shake=4;burst(W/2+s.tx*W*.3,H*.28+s.ty*H*.18,12);msg(s.saved?'SAVED!':'MISS!','bad')}save();hud();setTimeout(()=>{if((mode==='shootout'||mode==='tournament')&&shots>=5){const won=goals>=3;coins+=won?200:25;save();showResult(won?'ROUND WON':'ROUND LOST','Goals: '+goals+' / 5 • Score: '+score)}else showResult(ok?'GOAL!':s.saved?'SAVED!':'MISS!','Goals: '+goals+' • Streak: '+streak)},650)}
function next(){if((mode==='shootout'||mode==='tournament')&&shots>=5){level++;shots=0;goals=0;streak=0}else if(mode==='endless'){level=1+Math.floor(goals/3)}reset()}
function bind(id,fn){const e=$(id);if(e)e.addEventListener('click',fn)}bind('shootoutBtn',()=>start('shootout'));bind('tournamentBtn',()=>start('tournament'));bind('challengeBtn',()=>start('endless'));bind('nextBtn',next);bind('restartBtn',()=>start(mode));bind('backMenuBtn',backMenu);bind('shootBtn',shoot);bind('leftBtn',()=>aimX=clamp(aimX-.12,-1,1));bind('rightBtn',()=>aimX=clamp(aimX+.12,-1,1));bind('upBtn',()=>aimY=clamp(aimY-.1,.02,1));bind('downBtn',()=>aimY=clamp(aimY+.1,.02,1));bind('spinLeft',()=>spin=clamp(spin-.18,-1,1));bind('spinRight',()=>spin=clamp(spin+.18,-1,1));bind('bottomPlay',()=>start('shootout'));
let drag=false;function aim(x,y){if(state!=='aim')return;const g=goalRect();if(x<g.left-60||x>g.left+g.gw+60||y<g.top-60||y>g.top+g.gh+60)return;aimX=clamp((x-g.left-g.gw/2)/(g.gw/2),-1,1);aimY=clamp((y-g.top)/g.gh,.02,1)}c.addEventListener('pointerdown',e=>{drag=true;aim(e.clientX,e.clientY)});c.addEventListener('pointermove',e=>drag&&aim(e.clientX,e.clientY));addEventListener('pointerup',()=>drag=false);addEventListener('pointercancel',()=>drag=false);
function goalRect(){const m=W<650,gw=Math.min(W*(m?.88:.74),620),gh=Math.min(H*(m?.28:.31),240);return{left:W/2-gw/2,top:m?H*.18:H*.21,gw:gw,gh:gh}}
function stadium(){const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#041321');g.addColorStop(.42,'#163d57');g.addColorStop(.44,'#287f49');g.addColorStop(1,'#07502c');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);const h=H*.41;for(let i=0;i<16;i++){ctx.fillStyle=i%2?'#172833':'#263943';ctx.fillRect(i*W/16,h-H*.27,W/16-2,H*.19)}ctx.fillStyle='#116b38';ctx.fillRect(0,h,W,H-h);ctx.strokeStyle='rgba(255,255,255,.2)';ctx.lineWidth=2;ctx.beginPath();ctx.arc(W/2,H*.75,W*.28,Math.PI,0);ctx.stroke()}
function drawGoal(){const g=goalRect();ctx.fillStyle='rgba(220,240,245,.08)';ctx.fillRect(g.left,g.top,g.gw,g.gh);ctx.strokeStyle='#fff';ctx.lineWidth=W<650?5:6;ctx.strokeRect(g.left,g.top,g.gw,g.gh);ctx.strokeStyle='rgba(255,255,255,.24)';ctx.lineWidth=1;for(let i=1;i<18;i++){const x=g.left+g.gw*i/18;ctx.beginPath();ctx.moveTo(x,g.top);ctx.lineTo(x,g.top+g.gh);ctx.stroke()}for(let i=1;i<10;i++){const y=g.top+g.gh*i/10;ctx.beginPath();ctx.moveTo(g.left,y);ctx.lineTo(g.left+g.gw,y);ctx.stroke()}return g}
function player(x,y,color,s,k){ctx.save();ctx.translate(x,y);ctx.scale(s,s);const d=k?keeper.dive*18:0;ctx.rotate(k?keeper.dive*.08:0);ctx.fillStyle='rgba(0,0,0,.35)';ctx.beginPath();ctx.ellipse(0,72,30,8,0,0,Math.PI*2);ctx.fill();ctx.fillStyle=color;ctx.fillRect(-20,-18,40,50);ctx.fillStyle='#e0a17d';ctx.beginPath();ctx.arc(0,-39,18,0,Math.PI*2);ctx.fill();ctx.fillStyle='#251b18';ctx.beginPath();ctx.arc(0,-49,17,Math.PI,Math.PI*2);ctx.fill();ctx.strokeStyle=color;ctx.lineWidth=11;ctx.lineCap='round';ctx.beginPath();if(k){ctx.moveTo(-15,-4);ctx.lineTo(-43-d,-25);ctx.moveTo(15,-4);ctx.lineTo(43+d,-25)}else{ctx.moveTo(-15,-3);ctx.lineTo(-34,28);ctx.moveTo(15,-3);ctx.lineTo(34,28)}ctx.stroke();ctx.strokeStyle='#202020';ctx.lineWidth=10;ctx.beginPath();ctx.moveTo(-9,31);ctx.lineTo(-15,69);ctx.moveTo(9,31);ctx.lineTo(15,69);ctx.stroke();ctx.restore()}
function ball(x,y,r){ctx.save();ctx.translate(x,y);ctx.fillStyle='#f4f6f6';ctx.beginPath();ctx.arc(0,0,r,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#202020';ctx.lineWidth=Math.max(1,r*.1);ctx.stroke();ctx.restore()}
function draw(){ctx.save();if(shake)ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);stadium();const g=drawGoal();const kx=W/2+keeper.x*g.gw*.45;player(kx,g.top+g.gh*.68,'#15945e',W<650?.82:.98,true);let sx=W/2,sy=H*.76,tx=W/2+aimX*g.gw*.43,ty=g.top+aimY*g.gh,bx=sx,by=sy,br=W<650?14:18;if(shot){const q=clamp(shot.t/shot.dur,0,1),e=q*q*(3-2*q);tx=W/2+shot.tx*g.gw*.43;ty=g.top+shot.ty*g.gh;bx=sx+(tx-sx)*e+Math.sin(e*Math.PI)*spin*g.gw*.09;by=sy+(ty-sy)*e-Math.sin(e*Math.PI)*H*(W<650?.055:.08);br+=8*e;keeper.x+=(keeper.target-keeper.x)*.08}const pc=(items.find(i=>i[0]===kit)||items[0])[5];player(W/2,H*.68,pc,W<650?.88:1.12,false);ball(bx,by,br);if(state==='aim'){ctx.strokeStyle='#ffe52d';ctx.lineWidth=2;ctx.setLineDash([7,6]);ctx.beginPath();ctx.moveTo(bx,by);ctx.lineTo(tx,ty);ctx.stroke();ctx.setLineDash([]);ctx.beginPath();ctx.arc(tx,ty,18+Math.sin(performance.now()/130)*3,0,Math.PI*2);ctx.stroke()}if(flash){ctx.fillStyle='rgba(255,255,255,'+(flash*.1)+')';ctx.fillRect(g.left,g.top,g.gw,g.gh)}for(const p of particles){ctx.globalAlpha=Math.max(0,p.life);ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;ctx.restore()}
let last=performance.now();function loop(now){const dt=Math.min(.033,(now-last)/1000);last=now;if(state==='aim'){power+=pdir*dt*.9;if(power>=1){power=1;pdir=-1}if(power<=.08){power=.08;pdir=1}hud()}if(state==='flight'&&shot){shot.t+=dt;if(shot.t>=shot.dur)finish()}for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=240*dt;p.life-=dt}particles=particles.filter(p=>p.life>0);shake*=Math.pow(.05,dt);if(shake<.1)shake=0;flash=Math.max(0,flash-dt*2);draw();requestAnimationFrame(loop)}
function open(id){const e=$(id);if(e)e.classList.remove('hidden')}function renderShop(){const box=$('shopGrid');if(!box)return;box.innerHTML='';for(const i of items){const has=owned.includes(i[0]),active=i[2]==='shirt'?kit===i[0]:shoe===i[0],el=document.createElement('div');el.className='shopItem';el.innerHTML='<div class="itemIcon">'+i[3]+'</div><b>'+i[1]+'</b><small>'+i[6]+'</small><button class="buyBtn '+(active?'owned':'')+'">'+(active?'EQUIPPED':has?'EQUIP':'🪙 '+i[4])+'</button>';el.querySelector('button').onclick=()=>{if(!has){if(coins<i[4]){msg('Not enough coins','bad');return}coins-=i[4];owned.push(i[0])}if(i[2]==='shirt')kit=i[0];else shoe=i[0];save();renderShop();hud()};box.appendChild(el)}}
if($('storeBtn'))$('storeBtn').onclick=()=>{renderShop();open('store')};if($('statsBtn'))$('statsBtn').onclick=()=>open('statsPanel');if($('skillsBtn'))$('skillsBtn').onclick=()=>open('skillsPanel');if($('settingsBtn'))$('settingsBtn').onclick=()=>open('settingsPanel');if($('bottomRank'))$('bottomRank').onclick=()=>open('statsPanel');if($('rewardBtn'))$('rewardBtn').onclick=()=>{const d=new Date().toISOString().slice(0,10);if(localStorage.psReward===d){msg('Reward already collected','info');return}localStorage.psReward=d;coins+=100;save();hud();msg('+100 🪙 Daily reward','good')};if($('coinPlus'))$('coinPlus').onclick=()=>{coins+=25;save();hud();msg('+25 🪙 bonus','good')};document.querySelectorAll('.close').forEach(b=>b.onclick=()=>$(b.dataset.close).classList.add('hidden'));if($('resetBtn'))$('resetBtn').onclick=()=>{localStorage.removeItem('psCoins');localStorage.removeItem('psOwned');localStorage.removeItem('psKit');localStorage.removeItem('psShoe');location.reload()};hud();requestAnimationFrame(loop);
})();